### ISSUE TITLE
Wardrobe to handle whole look

### ISSUE THREAD

**Issue by cvuorinen** [probaton/habotica#38]
Instead of just equipment, it would be great if you could save the whole look of the avatar, including skin, hair etc. + background and maybe even pet/mount.

**Comment by probaton** [comment]
I figured it was only a matter of time before someone asked for this. Great idea, I even thought about building it this way from the start, but I wanted to start simple.

**Comment by cvuorinen** [comment]
Yep, totally understand. And it's nothing critical of course, but would nice to have.
