### ISSUE TITLE
FR: Only spam skill until boss is defeated

### ISSUE THREAD

**Issue by rakheepatel** [probaton/habotica#43]
I like the `Spam until I'm out of Mana` feature. For classes that are able to use skills to kill bosses (and I suppose you'd need to detect class somehow for this idea to work) it would be handy to _not_ spam until they're out of Mana, but to `Spam until the boss is dead`.

Requirements: 
- Detect class of current user
- Get bosses total health, current health

Complications:
How would you calculate how much damage a skill does? Would you do some math? Would you apply the skill once, see the difference it made in health, and use that to calculate how many more times the skill should be used? Would you apply the skill one at a time and keep applying until boss health is reduced to less than or equal to zero?

Just an idea, if you feel like it'd add value to the app.

**Comment by probaton** [comment]
That's actually a really cool idea. Unfortunately, I did some digging and wasn't able to come up with a conclusive way to determine whether or not a boss is dead. 

The only useful information available is which quest is currently in progress and how much damage you have pending. I might be able to cross-reference the quest name and determine how much total hp it has. However, without knowing how much damage it's already had, and how much damage the rest of your team has pending, there's no way to know how much damage needs to be done.
