### ISSUE TITLE
Wardrobe

### ISSUE THREAD

**Issue by probaton** [probaton/habotica#6]
It would be the most awesomest thing ever if I could store my current outfit and then re-equip it with the push of a button! The feature should allow me to store both my equipment and my costume, and also allow me to mass-equip to both slots. 

Bonus feature: allow individual slots to be selected with some sort of checkbox. E.g. save every gear slot except the offhand.

**Comment by cvuorinen** [comment]
Would be great to be able to automatically choose best equipment for max stats. E.g. if you want to cast skills that is based on STR, then before using that you could max out STR with best equipment combination possible and after using the skill you could return to overall best stats or a stored equipment set etc.

**Comment by probaton** [comment]
Oh wow. Never even crossed my mind. Interesting thought! Definitely worth looking into, but is sort of scope for this issue, so I created a new issue for it #19.

**Comment by probaton** [comment]
Feature implemented in 0f1e90129154bfaa9c5095749f2572c980d5399b
